### PR TITLE
Fix product hunt logo not centered

### PR DESCRIPTION
**Pull request by Lylekepkey**
## Summary

Product hunt logo
## Changes Made

Centered the logo 

## TODO

Nothing much 

## Motivation

To center the logo

## Screenshots/GIFs

image

## Checklist

Please ensure all of the following are completed before submitting the PR:

- [x] Code has been tested and verified.
- [x] Documentation has been updated to reflect the changes.
- [x] All tests pass successfully.
- [x] Code follows the project's coding guidelines and style.
- [x] The branch is up-to-date with the latest changes from the main branch.
- [x] Reviewed by at least one other contributor.

### CODE REVIEW

**Comment by aurora-care-bear** [comment]
Thanks for submitting a pull request!
We will review it as soon as possible.

**Review by Lylekepkey — COMMENTED** [review]
Resolved issue

**Review by 0xWDG — APPROVED** [review]
Works as expected.

**Comment by nanashili** [comment]
@0xWDG We really need a dark mode of PH

**Review by nanashili — APPROVED** [review]

**Comment by aurora-care-bear** [comment]
Hey @Lylekepkey,

Thanks for your contribution.
Your PR has been merged!
Your name will appear on https://auroraeditor.com/#contributors in a few moments, if you have contributed to the editor.

Thanks again for your contribution!

Kind Regards,
Aurora Editor Team.

**Comment by nanashili** [comment]
On another note I just noticed the download button isn't hidden on platforms that is not Mac....

**Comment by 0xWDG** [comment]
> @0xWDG We really need a dark mode of PH

True, I'm unsure if they support it.. 

I will look into it later

**Pull request merged**
