### PR TITLE
Issue #377 Add Correct Visibility Value, Add Mastodon Link, Styles

### PR DESCRIPTION
**Pull request by alexchrysovergis**
## Summary

This PR corrects the visibility of the unstyled Mastodon link at the bottom of the website and adds it into the ```<aside class="section socials-router-links">``` element.

## Changes Made

- Corrected the visibility property to hide the original unstyled link.
- Added the Mastodon link inside the <aside class="section socials-router-links"> element alongside the other links.
- Added a Y-Axis shake animation on the Mastadon logo on hover.

## TODO

N/A

## Motivation

Improves the visual unity of the website and makes the link more accessible to users. 

## Testing

- Tested it with Responsive Dev Tools.
- Verified that the link works as expected.

## Screenshots/GIFs

Before:
image
After:
image

## Checklist

- [x] Code has been tested and verified.
- [ ] Documentation has been updated to reflect the changes.
- [x] All tests pass successfully.
- [x] Code follows the project's coding guidelines and style.
- [x] The branch is up-to-date with the latest changes from the main branch.
- [ ] Reviewed by at least one other contributor.

## Related Issues

This PR addresses the following issue(s): Issue #377

## Additional Notes

The icon is from [UXWing](https://uxwing.com/mastodon-icon/), which has a license stating that "All icons on this site can be used in personal, commercial, and client projects without any attribution or credit."

### CODE REVIEW

**Comment by aurora-care-bear** [comment]
Thanks for submitting a pull request!
We will review it as soon as possible.

**Comment by 0xWDG** [comment]
Hey @alexchrysovergis thanks for this PR 😊 
Your changes will be live in about 5 minutes, your name will be added to the contributor list as well.

and since it's hacktoberfest I added the appropriate tags if you are participating with it 😊

thanks! 🙏

**Comment by aurora-care-bear** [comment]
Hey @alexchrysovergis,

Thanks for your contribution.
Your PR has been merged!
Your name will appear on https://auroraeditor.com/#contributors in a few moments, if you have contributed to the editor.

Thanks again for your contribution!

Kind Regards,
Aurora Editor Team.

**Comment by alexchrysovergis** [comment]
Thank you for adding the tags! I'm excited to contribute and look forward to helping with anything else that comes up in the future.

**Pull request merged**
