### PR TITLE
Fixed GitHub icon (Old icon violated their Logo TOS)

### PR DESCRIPTION
**Pull request by Blackhole1123**

### CODE REVIEW

**Comment by nanashili** [comment]
Image of new logo and the link to where it states it is a violation

**Comment by nanashili** [comment]
It breaks on dark mode, please fix that

**Comment by 0xWDG** [comment]
The old icon is cute 🥰

**Comment by nanashili** [comment]
Closing for now, till I get a response from @Blackhole1123

**Pull request closed without merging**
